// The season -> colour join table: generated by scripts/build-season-colors.ts
// from the rules, committed, and validated here at load.
//
// The band check takes `bandFor` as a PARAMETER rather than importing it. The
// thresholds that turn a distance into "close" belong with the distance metric
// in src/color/colorDistance.ts, which imports culori and so cannot be reached
// from the pure kernel. Injecting it keeps one copy of those numbers instead
// of two that would drift.
import type { FitBand } from './types'

export const SEASON_COLORS_SCHEMA_VERSION = 1

export interface SeasonColor {
  seasonId: string
  colorId: number
  /** Distance to the nearest ideal colour of that season. */
  distance: number
  band: FitBand
}

function fail(msg: string): never {
  throw new Error(`Invalid season-colors.json: ${msg}`)
}

export function validateSeasonColors(
  data: unknown,
  seasonIds: Set<string>,
  colorIds: Set<number>,
  bandFor?: (distance: number) => FitBand,
): SeasonColor[] {
  if (typeof data !== 'object' || data === null || Array.isArray(data)) fail('not an object')
  const d = data as { schemaVersion?: number; description?: string; entries?: unknown }
  if (d.schemaVersion !== SEASON_COLORS_SCHEMA_VERSION) {
    fail(`schemaVersion ${d.schemaVersion} != expected ${SEASON_COLORS_SCHEMA_VERSION}`)
  }
  if (typeof d.description !== 'string' || !d.description) fail('description missing')
  if (!Array.isArray(d.entries) || d.entries.length === 0) fail('entries missing or empty')

  const seen = new Set<string>()
  for (const raw of d.entries) {
    const e = raw as SeasonColor
    if (!seasonIds.has(e.seasonId)) fail(`row references unknown season "${e.seasonId}"`)
    if (!colorIds.has(e.colorId)) fail(`row references unknown colour ${e.colorId}`)
    const key = `${e.seasonId}/${e.colorId}`
    if (seen.has(key)) fail(`duplicate row ${key}`)
    seen.add(key)
    if (typeof e.distance !== 'number' || !Number.isFinite(e.distance) || e.distance < 0) {
      fail(`row ${key} has a bad distance ${e.distance}`)
    }
    // A band that disagrees with its own distance means the table was
    // hand-edited or generated by a different set of thresholds. Either way
    // the visitor would be told a wrong thing about how good the match is.
    if (bandFor && bandFor(e.distance) !== e.band) {
      fail(`row ${key} has band "${e.band}" but distance ${e.distance} implies "${bandFor(e.distance)}"`)
    }
  }
  return d.entries as SeasonColor[]
}

/** Rows for one season, best fit first (the file is already sorted). */
export function colorsForSeason(entries: SeasonColor[], seasonId: string): SeasonColor[] {
  return entries.filter((e) => e.seasonId === seasonId)
}
