// Renders the PCCS structure as sRGB: 24 hues x 12 chromatic tones = 288
// colours, each at the centre of its tone's band.
//
// The output is OUR RENDERING, not JCRI's chip values. PCCS chips are physical
// paper measured under illuminant C; these are computed from the published
// band definitions through the mapping in src/color/pccsMap.ts. Anyone
// comparing them to a real PCCS colour card should expect them to be close,
// not identical. The file says so in its own description, because it is
// exactly the kind of data that gets copied out of context.
//
// Regenerate with: npm run build-pccs-grid
import { readFileSync, writeFileSync } from 'node:fs'
import { pccsToHex } from '../src/color/pccsMap'
import { validatePccsHues, validatePccsTones } from '../src/core/pccs'
import { sourceIds, validateSources } from '../src/core/sources'

const read = (p: string) => JSON.parse(readFileSync(p, 'utf8'))

const ids = sourceIds(validateSources(read('data/reference/sources.json')))
const hues = validatePccsHues(read('data/reference/pccs-hues.json'), ids)
const tones = validatePccsTones(read('data/reference/pccs-tones.json'), ids).filter(
  (t) => !t.achromatic,
)

// The tone's canonical position, NOT the centre of its band — see the note in
// pccs-tones.json. Using the midpoint rendered `bright` as a washed-out pink.
const cells = hues.flatMap((h) =>
  tones.map((t) => {
    const { lightness, saturation } = t.representative!
    return {
      hue: h.n,
      hueAbbr: h.abbr,
      tone: t.abbr,
      toneName: t.en,
      lightness,
      saturation,
      hex: pccsToHex(h.n, lightness, saturation),
    }
  }),
)

const out = {
  schemaVersion: 1,
  description:
    'The PCCS hue/tone grid rendered as sRGB: 24 hues x 12 chromatic tones, each colour taken at the centre of its tone band. GENERATED by scripts/build-pccs-grid.ts from pccs-hues.json and pccs-tones.json — do not hand-edit. IMPORTANT: these are OUR RENDERING of the published PCCS structure, not the Japan Color Research Institute’s chip values. PCCS chips are physical paper measured under illuminant C; these are computed through the Lab mapping documented in src/color/pccsMap.ts. Expect them to be close to a real PCCS colour card, not identical.',
  sources: ['wikipedia-ja-pccs', 'shikisai101-pccs', 'jcri'],
  generatedBy: 'scripts/build-pccs-grid.ts',
  cells,
}

writeFileSync('data/reference/pccs-grid.json', `${JSON.stringify(out, null, 2)}\n`)
console.log(`Wrote ${cells.length} cells to data/reference/pccs-grid.json`)
