// Builds the season -> colour join table from the rules.
//
// This is the file the old hand-curated seasons.json used to be, except nobody
// picks anything: run the rules over the book and write down what falls out,
// with the fit distance attached. Committed to the repo so it can be read,
// joined against and used on its own; tests/seasonColors.test.ts regenerates
// it and fails on any diff, so it cannot drift from the rules that produced it.
//
// Regenerate with: npm run build-season-colors
import { readFileSync, writeFileSync } from 'node:fs'
import { seasonMembers } from '../src/color/seasonFit'
import { validatePccsGrid, validatePccsHues, validatePccsTones } from '../src/core/pccs'
import { validateSeasonRules } from '../src/core/seasons'
import { sourceIds, validateSources } from '../src/core/sources'
import type { ColorRecord } from '../src/core/types'

const read = (p: string) => JSON.parse(readFileSync(p, 'utf8'))

const ids = sourceIds(validateSources(read('data/reference/sources.json')))
const hues = validatePccsHues(read('data/reference/pccs-hues.json'), ids)
const tones = validatePccsTones(read('data/reference/pccs-tones.json'), ids)
const grid = validatePccsGrid(read('data/reference/pccs-grid.json'), ids, hues, tones)
const rules = validateSeasonRules(
  read('data/curated/season-rules.json'),
  new Set(tones.map((t) => t.abbr)),
  ids,
)
const colors: ColorRecord[] = read('data/processed/colors-data.json').colors

export function buildSeasonColors() {
  const entries = rules.subSeasons.flatMap((sub) =>
    seasonMembers(rules, sub, grid, tones, colors).map((m) => ({
      seasonId: sub.id,
      colorId: m.colorId,
      // Rounded: the join table is for reading and joining, and six decimal
      // places of a perceptual distance is false precision that would also
      // make the file churn on every floating-point breeze.
      distance: Number(m.distance.toFixed(4)),
      band: m.band,
    })),
  )

  return {
    schemaVersion: 1,
    description:
      'Season -> colour join table. GENERATED by scripts/build-season-colors.ts from data/curated/season-rules.json and the PCCS reference data — do not hand-edit. A row means: this colour of Wada\'s book belongs to this season by the rule (right temperature half, right PCCS tone), and `distance` is how far it sits from the nearest ideal colour of that season, in the units of src/color/colorDistance.ts. IMPORTANT: these are the CLOSEST MATCHES IN THE BOOK, not season colours. Wada\'s 1933 book is a saturated pigment book — only 11 of its 157 colours are genuinely muted — so the soft seasons in particular are served by approximations. The `band` says how good each one is; do not drop it when using this data.',
    sources: ['whatcolorssuitme-korean', 'colorme-korean', 'wikipedia-ja-pccs'],
    generatedBy: 'scripts/build-season-colors.ts',
    entries,
  }
}

export const SEASON_COLORS_PATH = 'data/processed/season-colors.json'

/** Serialised exactly as the committed file, so a test can compare strings. */
export function serialise(out: ReturnType<typeof buildSeasonColors>): string {
  return `${JSON.stringify(out, null, 2)}\n`
}

// Only write when run as a script. tests/seasonColors.test.ts imports the
// builder to check the committed file is current, and must not rewrite the
// very file it is checking — that would make the test pass by definition.
const runDirectly = process.argv[1]?.endsWith('build-season-colors.ts')

if (runDirectly) {
  const out = buildSeasonColors()
  writeFileSync(SEASON_COLORS_PATH, serialise(out))
  console.log(`Wrote ${out.entries.length} rows to ${SEASON_COLORS_PATH}`)
  for (const sub of rules.subSeasons) {
    const rows = out.entries.filter((e) => e.seasonId === sub.id)
    const good = rows.filter((e) => e.band === 'very close' || e.band === 'close').length
    console.log(
      `  ${sub.id.padEnd(14)} ${String(rows.length).padStart(3)} colours, ${good} a good fit`,
    )
  }
}
