// Seeds data/curated/seasons.json — ONCE.
//
// After this runs, the JSON is owned by hand: edited by the owner, or audited
// by another agent against published sources. It is not part of the build and
// re-running it will overwrite curation. The regions below are the ones used in
// the brainstorm mockup (docs/superpowers/specs/2026-07-28-personal-color-
// harmony-comparison.html), and they have NO published source — they are our
// invention. That is exactly why the result lives in a file anyone can inspect
// and correct rather than buried in TypeScript.
//
// Run with: npm run seed-seasons
import { writeFileSync, mkdirSync } from 'node:fs'
import { converter } from 'culori'
import processed from '../data/processed/colors-data.json'

const toLab = converter('lab')

interface Region {
  id: string
  name: string
  undertone: 'warm' | 'neutral' | 'cool'
  depth: 'light' | 'medium' | 'deep'
  chroma: 'high' | 'medium' | 'low'
  hue: [number, number]
  L: [number, number]
  C: [number, number]
}

const REGIONS: Region[] = [
  { id: 'deep-autumn', name: 'Deep Autumn', undertone: 'warm', depth: 'deep', chroma: 'high', hue: [15, 95], L: [15, 58], C: [20, 70] },
  { id: 'true-autumn', name: 'True Autumn', undertone: 'warm', depth: 'medium', chroma: 'medium', hue: [25, 90], L: [30, 68], C: [25, 65] },
  { id: 'soft-autumn', name: 'Soft Autumn', undertone: 'warm', depth: 'medium', chroma: 'low', hue: [20, 95], L: [35, 72], C: [10, 40] },
  { id: 'warm-spring', name: 'Warm Spring', undertone: 'warm', depth: 'light', chroma: 'medium', hue: [20, 95], L: [55, 92], C: [30, 75] },
  { id: 'light-spring', name: 'Light Spring', undertone: 'warm', depth: 'light', chroma: 'low', hue: [15, 110], L: [60, 95], C: [15, 50] },
  { id: 'clear-spring', name: 'Clear Spring', undertone: 'warm', depth: 'light', chroma: 'high', hue: [0, 120], L: [45, 88], C: [40, 90] },
  { id: 'cool-summer', name: 'Cool Summer', undertone: 'cool', depth: 'medium', chroma: 'medium', hue: [180, 330], L: [45, 85], C: [10, 40] },
  { id: 'light-summer', name: 'Light Summer', undertone: 'cool', depth: 'light', chroma: 'low', hue: [170, 340], L: [60, 95], C: [8, 35] },
  { id: 'soft-summer', name: 'Soft Summer', undertone: 'cool', depth: 'medium', chroma: 'low', hue: [160, 340], L: [40, 80], C: [6, 30] },
  { id: 'deep-winter', name: 'Deep Winter', undertone: 'cool', depth: 'deep', chroma: 'high', hue: [200, 360], L: [12, 55], C: [20, 70] },
  { id: 'cool-winter', name: 'Cool Winter', undertone: 'cool', depth: 'deep', chroma: 'medium', hue: [190, 350], L: [25, 75], C: [25, 75] },
  { id: 'clear-winter', name: 'Clear Winter', undertone: 'cool', depth: 'light', chroma: 'high', hue: [180, 360], L: [18, 80], C: [45, 95] },
]

function lch(hex: string) {
  const { l, a, b } = toLab({
    mode: 'rgb',
    r: parseInt(hex.slice(1, 3), 16) / 255,
    g: parseInt(hex.slice(3, 5), 16) / 255,
    b: parseInt(hex.slice(5, 7), 16) / 255,
  })
  return { L: l, C: Math.hypot(a, b), h: ((Math.atan2(b, a) * 180) / Math.PI + 360) % 360 }
}

// Widen a region until it holds at least this many colours. A season nobody can
// wear is worse than a slightly loose one, and an empty palette fails
// validation anyway.
const MIN_PER_SEASON = 6

function collect(r: Region, slack: number): number[] {
  const [hLo, hHi] = r.hue
  return processed.colors
    .filter((c) => {
      const { L, C, h } = lch(c.hex)
      const hueOk = hLo <= hHi
        ? h >= hLo - slack * 2 && h <= hHi + slack * 2
        : h >= hLo - slack * 2 || h <= hHi + slack * 2
      return hueOk
        && L >= r.L[0] - slack && L <= r.L[1] + slack
        && C >= r.C[0] - slack && C <= r.C[1] + slack
    })
    .map((c) => c.id)
}

const seasons = REGIONS.map((r) => {
  let slack = 0
  let colorIds = collect(r, slack)
  while (colorIds.length < MIN_PER_SEASON && slack < 40) {
    slack += 5
    colorIds = collect(r, slack)
  }
  if (slack > 0) console.log(`  ${r.id}: widened by ${slack} to reach ${colorIds.length}`)
  return {
    id: r.id, name: r.name,
    undertone: r.undertone, depth: r.depth, chroma: r.chroma,
    colorIds: colorIds.sort((a, b) => a - b),
  }
})

const out = {
  schemaVersion: 1,
  note: [
    'HAND-CURATED. Edit this file directly — it is read by the app and is not',
    'regenerated by the build. Re-running scripts/seed-seasons.ts OVERWRITES any',
    'curation done here.',
    '',
    'These twelve palettes have NO published source. They were seeded from',
    'hue/lightness/chroma regions we invented, and the site says so on the',
    'result page and in About. Correcting them against a real source is a',
    'welcome change and needs no code.',
    '',
    'colorIds refer to data/processed/colors-data.json. Membership is',
    'many-to-many: a colour may belong to several seasons.',
  ].join(' '),
  seasons,
}

mkdirSync('data/curated', { recursive: true })
writeFileSync('data/curated/seasons.json', JSON.stringify(out, null, 2) + '\n')
console.log(`\nwrote data/curated/seasons.json — ${seasons.length} seasons`)
for (const s of seasons) console.log(`  ${s.name.padEnd(14)} ${s.colorIds.length} colours`)
